### ISSUE TITLE
HTTP request does not close properly

### ISSUE THREAD

**Issue by hatkirby** [hatkirby/gen3uploader#3]
The extractor does not properly end the HTTP session with the webserver. This does not have an effect on the success of sending the data, but it does cause Rails to display the following error message in its logs:

```
[2017-09-26 17:18:47] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:12 
	/Users/hatkirby/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
	/Users/hatkirby/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
	/Users/hatkirby/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
```

**Comment by hatkirby** [comment]
This might actually be a problem with Webrick, and not with either Rails or the extractor.
